---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: myargocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/vfarcic/argo-combined-demo.git
    targetRevision: HEAD
    path: production
  destination:
    server: https://5e4c3dc0-6928-4611-8827-ba81cdd36bb9.k8s.ondigitalocean.com
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  namespace: myargocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    repoURL: https://github.com/vfarcic/argo-combined-demo.git
    targetRevision: HEAD
    path: staging
  destination:
    server: https://5e4c3dc0-6928-4611-8827-ba81cdd36bb9.k8s.ondigitalocean.com
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

