apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: argo-workflows/overlays/production
    repoURL: https://github.com/kejalsuthar/argo-combined-demo
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://0cf74905-f1a4-4ea6-8674-1651b9abe17b.k8s.ondigitalocean.com
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

