apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: argo-workflows/overlays/production
    repoURL: https://github.com/kejalsuthar/argo-combined-demo
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://5e4c3dc0-6928-4611-8827-ba81cdd36bb9.k8s.ondigitalocean.com
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

