apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app
  namespace: myargocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/vfarcic/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - vfarcic/argo-combined-app:latest
  destination:
    server: https://5e4c3dc0-6928-4611-8827-ba81cdd36bb9.k8s.ondigitalocean.com
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
