apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/tree/master/manifests/crds
- github.com/argoproj/tree/master/manifests/base
- github.com/argoproj/tree/master/manifests/cluster-rbac/
namespace: argocd
