apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: sealed-secrets
    repoURL: https://github.com/kejalsuthar/argocd-production
    targetRevision: HEAD
  destination:
    server: https://0cf74905-f1a4-4ea6-8674-1651b9abe17b.k8s.ondigitalocean.com
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

