apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: sealed-secrets
    repoURL: https://github.com/kejalsuthar/argocd-production
    targetRevision: HEAD
  destination:
    server: https://5e4c3dc0-6928-4611-8827-ba81cdd36bb9.k8s.ondigitalocean.com
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

